// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DTHexZzFI5vck0jsQUfaqMC6ARPBuM8',
    appId: '1:802199677448:web:93d503f6ca86ca00417fbd',
    messagingSenderId: '802199677448',
    projectId: 'push-d9e0b',
    authDomain: 'push-d9e0b.firebaseapp.com',
    storageBucket: 'push-d9e0b.firebasestorage.app',
    measurementId: 'G-HDYC5V1FB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9qifP-w7_FV3dhvV3p8ZoOdZS4zYEW14',
    appId: '1:802199677448:android:37fd6ac5088049e4417fbd',
    messagingSenderId: '802199677448',
    projectId: 'push-d9e0b',
    storageBucket: 'push-d9e0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpaXEyknexSFPzBoz14w48u42RzBDaRc',
    appId: '1:802199677448:ios:19aaeb79faaafa49417fbd',
    messagingSenderId: '802199677448',
    projectId: 'push-d9e0b',
    storageBucket: 'push-d9e0b.firebasestorage.app',
    iosBundleId: 'com.tktechnology.push',
  );
}
